services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyayaai-api

    ports:
      - "8000:8000"

    env_file:
      - .env.docker

    volumes:
      - .:/app
      - venv_data:/app/.venv


    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      mailhog:
        condition: service_started

    restart: unless-stopped

    networks:
      - nyayaai-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyayaai-worker

    command: celery -A app.workers.celery_app worker --loglevel=info

    env_file:
      - .env.docker

    volumes:
      - .:/app
      - venv_data:/app/.venv

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    restart: unless-stopped

    networks:
      - nyayaai-network

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyayaai-beat

    command: celery -A app.workers.celery_app beat --loglevel=info

    env_file:
      - .env.docker

    volumes:
      - .:/app
      - venv_data:/app/.venv

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    restart: unless-stopped

    networks:
      - nyayaai-network

  postgres:
    image: pgvector/pgvector:pg16

    container_name: nyayaai-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nyayaai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
      - nyayaai-network

  redis:
    image: redis:7-alpine

    container_name: nyayaai-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

    networks:
      - nyayaai-network

  minio:
    image: minio/minio:latest

    container_name: nyayaai-minio

    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

    restart: unless-stopped

    networks:
      - nyayaai-network

  mailhog:
    image: mailhog/mailhog:latest

    container_name: nyayaai-mailhog

    ports:
      - "1025:1025"
      - "8025:8025"

    restart: unless-stopped

    networks:
      - nyayaai-network

volumes:
  postgres_data:
  minio_data:
  venv_data:

networks:
  nyayaai-network:
    driver: bridge