"""updated models till module 7

Revision ID: ad4fa35655f8
Revises: f1fdb9038ecb
Create Date: 2026-08-20 14:49:39.734658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'ad4fa35655f8'
down_revision: Union[str, Sequence[str], None] = 'f1fdb9038ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure pgvector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_number', sa.String(length=100), nullable=True))
    op.add_column('cases', sa.Column('court_type', sa.String(length=100), nullable=True))
    op.add_column('cases', sa.Column('case_type', sa.String(length=100), nullable=True))
    op.add_column('cases', sa.Column('sync_failure_count', sa.Integer(), nullable=False))
    op.add_column('cases', sa.Column('consecutive_sync_failures', sa.Integer(), nullable=False))
    op.add_column('cases', sa.Column('last_sync_error', sa.String(), nullable=True))
    op.drop_constraint(op.f('clients_user_id_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('extracted_text', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('ocr_error', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bar_council_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bar_council_id')
    op.drop_column('documents', 'ocr_error')
    op.drop_column('documents', 'extracted_text')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_user_id_fkey'), 'clients', 'users', ['user_id'], ['id'])
    op.drop_column('cases', 'last_sync_error')
    op.drop_column('cases', 'consecutive_sync_failures')
    op.drop_column('cases', 'sync_failure_count')
    op.drop_column('cases', 'case_type')
    op.drop_column('cases', 'court_type')
    op.drop_column('cases', 'case_number')
    # ### end Alembic commands ###
