"""added models for module 4&5

Revision ID: efe5eeb0cc1d
Revises: a4bc3eb5d68b
Create Date: 2026-08-01 17:26:13.417393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efe5eeb0cc1d'
down_revision: Union[str, Sequence[str], None] = 'a4bc3eb5d68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure pgvector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecourts_lookup_cache',
    sa.Column('cnr', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecourts_lookup_cache_cnr'), 'ecourts_lookup_cache', ['cnr'], unique=True)
    op.create_table('case_notes',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_notes_tenant_id'), 'case_notes', ['tenant_id'], unique=False)
    op.add_column('clients', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'clients', ['user_id'])
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'user_id')
    op.drop_index(op.f('ix_case_notes_tenant_id'), table_name='case_notes')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_ecourts_lookup_cache_cnr'), table_name='ecourts_lookup_cache')
    op.drop_table('ecourts_lookup_cache')
    # ### end Alembic commands ###
