"""add ocr_error and case sync failure tracking

`documents.ocr_error` records *why* extraction failed; `ocr_status` alone cannot tell
an unconfigured-OCR scan apart from a corrupt file. The three `cases` columns are what
eCourts sync backs off on — the consecutive run drives the retry decision, the lifetime
total is the "this CNR has always been flaky" signal.

Both counters carry a `server_default` because the deployed `cases` table has rows: a
NOT NULL ADD COLUMN without one fails outright on a non-empty table.

Revision ID: 239ec022263b
Revises: aff0fc9b19b9
Create Date: 2026-08-22 22:39:58.409936+05:30
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "239ec022263b"
down_revision: str | None = "aff0fc9b19b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cases",
        sa.Column("sync_failure_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "cases",
        sa.Column(
            "consecutive_sync_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.add_column("cases", sa.Column("last_sync_error", sa.Text(), nullable=True))
    op.add_column("documents", sa.Column("ocr_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "ocr_error")
    op.drop_column("cases", "last_sync_error")
    op.drop_column("cases", "consecutive_sync_failures")
    op.drop_column("cases", "sync_failure_count")
    # ### end Alembic commands ###
