from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    FORBIDDEN_ROLE = "FORBIDDEN_ROLE"

    CASE_NOT_FOUND = "CASE_NOT_FOUND"
    FIRM_NOT_FOUND = "FIRM_NOT_FOUND"
    CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
    CNR_INVALID = "CNR_INVALID"
    UPGRADE_REQUIRED = "UPGRADE_REQUIRED"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"